### ISSUE TITLE
iOS: registration id will invalid when post notification payload

### ISSUE THREAD

**Issue by yutin1987** [google/gcm#106]
Use (GcmExample.xcodeproj) to register GCM from iOS app, can get registration id, and post data payload is ok.
but post notification payload, got InternalServerError / NotRegistered.

I cannot alert notification on my ios app.

https://www.youtube.com/watch?v=66GkTHdphzQ

**Comment by silvolu** [comment]
@yutin1987 which version of the pod are you using?

**Comment by silvolu** [comment]
Actually, can you make sure that you are setting the correct value for `kGGLInstanceIDAPNSServerTypeSandboxOption` when you call `tokenWithAuthorizedEntity` (example [here](https://github.com/googlesamples/google-services/blob/master/ios/gcm/GcmExample/AppDelegate.m#L150)? It should be true if you are using a  development certificate, false if you are using a production certificate. If you send a request using the wrong pair of certificate/serverType, the first one will fail because the APNs server doesn't accept it, and at that point we mark your token as invalid and remove it (hence the following NotRegistered errors)

**Comment by yutin1987** [comment]
@silvolu Thanks, it works.
I missed the message "but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist"

**Comment by jamilshazad** [comment]
Facing same issue how can i resolve it i am using Development Certificate and i have set kGGLInstanceIDAPNSServerTypeSandboxOption value to YES,But still getting invalid Registration?

**Comment by mohitsharma0690** [comment]
@jamilshazad what is the request you're trying to send?
