### ISSUE TITLE
Add support for content_available to Java library

### ISSUE THREAD

**Issue by PaulMazzuca** [google/gcm#162]
Feature request for content_available option for iOS clients.  This allows iOS clients to update in the background when receiving a push notification.   For GCM, it is a boolean value for the key "content_available". 

ref: https://developers.google.com/cloud-messaging/http-server-ref

**Comment by silvolu** [comment]
I'm not sure I understand your feature request: as described in the ref for the `content_available` field, "On iOS, use this field to represent content-available in the APNS payload.". Have you tried and it's not working?

**Comment by PaulMazzuca** [comment]
I guess my question is where should the "content_available" key be set
using the the gcm-server API? I have it working when I use my forked
version of the code:

notifyBuilder.title("title").body("body").badge(10).sound("default")
.contentAvailable(true);

However, maybe this is not the correct way to do it?

**Comment by silvolu** [comment]
Oh ok, I got confused because I didn't understand you were referring to the Java library. To reflect the parameters' structure of the GCM API, it should be in the `Message` builder rather than the `Notification` builder. Assigning this to @kroikie and renaming the issue for clarity, feel free to send a Pull Request if you want :)
