### ISSUE TITLE
GCM based server and Firebase client (iOS)

### ISSUE THREAD

**Issue by U85** [google/gcm#218]
I have limitations where I cannot use cocoapods for GCM. I know Firebase is a higher version of GCM and Firebase SDK can be installed without use of cocoapods. My query is : I have a server implementation based on GCM and I want my iOS app to use Firebase SDK. Will the GCM based server be able to send notifications to app without any change?

**Comment by ogeidix** [comment]
Yes. GCM server is compatible with FCM.
If you can update the endpoint, but it's not required.
https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update_server_endpoints

**Comment by davidalonso** [comment]
@ogeidix is this affirmation still valid nowadays? Now there's a separated Firebase Console and the entire project has to be imported there. Is there any necessary change to be performed to a server with GCM implementation to be able to send messages to a Firebase iOS client app?

Does Sender ID change when importing Google Project to Firebase console?

Will an existing Android app still be receiving notifications as it does before importing project to Firebase?

I'm seeing myself obligated to update because of an expired iOS Apns certificate. Is there any way to update the existing GoogleService-Info.plist without updating to Firebase?

**Comment by ogeidix** [comment]
> @ogeidix  is this affirmation still valid nowadays? 

yes.

> Now there's a separated Firebase Console and the entire project has to be imported there. Is there any necessary change to be performed to a server with GCM implementation to be able to send messages to a Firebase iOS client app?

No. If you can, update the endpoint, but it's not required.
https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update_server_endpoints

> Does Sender ID change when importing Google Project to Firebase console?

No.

> Will an existing Android app still be receiving notifications as it does before importing project to Firebase?

Yes.

> I'm seeing myself obligated to update because of an expired iOS Apns certificate. Is there any way to update the existing GoogleService-Info.plist without updating to Firebase?

The best way would be to import the project in Firebase.
