### ISSUE TITLE
java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()'

### ISSUE THREAD

**Issue by HuuThang91** [google/gcm#228]
I've implemented GCM notifications on my app and it causes the application to crash with the following logcat: 
java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears ....)
Here is my gradle 
......compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:support-compat:24.2.0'
    compile 'com.android.support:design:24.2.0'

   compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile 'com.facebook.fresco:fresco:0.9.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
........................................................................................................................................

**Comment by jstrassmayr** [comment]
same here

**Comment by brspurri** [comment]
Same +1

**Comment by ogeidix** [comment]
This issue is covered by multiple stack overflow questions.
This is one: 
http://stackoverflow.com/questions/40904466/java-lang-illegalaccesserror-method-void-android-support-v4-content

In short this is the check list:
1. check that you are using the latest version of Firebase Messaging
2. check that you are using the same version for all the firebase & google play services libraries
3. check that other dependencies are not adding libraries with old / wrong versions

to check 3 you can use:  ./gradlew app:dependencies

**Comment by byteHxC** [comment]
**jbksd
**

**Comment by byteHxC** [comment]
> chido men
