### ISSUE TITLE
Why was the GCM server Java code removed?

### ISSUE THREAD

**Issue by samvrlewis** [google/gcm#59]
There are numerous references in the official GCM documentation to gcm-server java samples that was previously avaliable on Google code: http://code.google.com/p/gcm

It looks like these used to be avaliable in this repo but were removed in https://github.com/google/gcm/commit/391d61f047e509f130473714864c4293e1b5ee22

Why was all this code removed? Has the gcm-server.jar package been depreciated? Is there anything I should be using in its place?

**Comment by dbaravalle** [comment]
+1
¿Why? ¿New samples or lib are coming?

**Comment by xuwei-k** [comment]
+1

**Comment by maiha** [comment]
:+1:

**Comment by Tomo-Hadi-Sutomo** [comment]
No. It is not removed. The service is still a live.

**Comment by xuwei-k** [comment]
> The service is still a live.

yes. the service is still a live, but code removed.

**Comment by dbaravalle** [comment]
Exactly, sample codes of server side and client side has been removed
Why? Has the gcm-server.jar package been deprecated? 
New samples or lib are coming?

**Comment by ZakTaccardi** [comment]
seriously, what is going on here?? I have an app engine server, and I need some java code to implement GCM 3.0 to send downstream messages.

The current release of gcm-server (1.0.2) does not have support for GCM 3.0. What is going on?

**Comment by dbaravalle** [comment]
+1, 
Please, give us some feedback, thank you

**Comment by micheleorsi** [comment]
+1
I am interested as well!

**Comment by tjohns** [comment]
Hey folks, sorry about that. We were cleaning out some of the old samples that we wanted to deprecate (since they didn't use best practices), and accidently removed the REST server code.

The gcm-server.jar package has been restored. You can find it in /client-libraries/java/rest-client.

We're currently rewriting the GCM samples to use the latest advice from the GCM documentation, as well as add additional samples for iOS. In the meantime, the best sample is the "GCM Quickstart" sample...

Android:
Docs: https://developers.google.com/cloud-messaging/android/start
Code: https://github.com/googlesamples/google-services/tree/master/android/gcm

iOS:
Docs: https://developers.google.com/cloud-messaging/ios/start
Code: https://github.com/googlesamples/google-services/tree/master/ios/gcm

**Comment by micheleorsi** [comment]
That's great @tjohns! But am I wrong or at the moment there is just your wrapper (com.google.android.gcm.server package)? 
I mean before there was also a couple of Servlet that were very important for us in order to understand how to use the Sender class and the best practices for using:
- multicastResult.getCanonicalIds()
- multicastResult.getFailure()

Thanks!

**Comment by AndreaPravato** [comment]
+1
