### ISSUE TITLE
Notifications tag does'nt work

### ISSUE THREAD

**Issue by giuseppesorce** [google/gcm#62]
HI, i tryed this example

https://github.com/googlesamples/google-services/tree/master/android/gcm

it work but only when server send json with tag 'data', when server sends json with tag 'notification' doesn't work.

**Comment by mnemonicflow** [comment]
Indeed, this seems to be the case. I've tested with a payload as follows:

```
send_queue.append({'to': REGISTRATION_ID,
                   'message_id': random_id(),
                   "notification" : {
                      "body" : "Hello from Server! What's going?",
                      "title" : "Hello from Server!",
                      "icon" : "@drawable/ic_school_white_48dp",
                      "sound": "default",
                      "color": "#03A9F4"
                    },
                   'data': { 'message': "Hello" } })
```

The notification is displayed by the system, but the onMessageReceived(String from, Bundle data) method of the GcmListenerService implemention doesn't get called

In AndroidManifest.xml MyGcmListenerService is defined as follows:
```
 <!-- [START gcm_listener] -->
        <service
            android:name="com.company.myapp.service.MyGcmListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <!-- [END gcm_listener] -->
```

The server reference payload docs (https://developers.google.com/cloud-messaging/server#payload) says:
`The app server can send a message including both notifications and data payloads. In such cases, GCM handles displaying the notification payload and the client app handles the data payload.`

The **"the client app handles the data payload"** part doesn't work.

**Comment by alibitek** [comment]
I think this might be related to #63

**Comment by alibitek** [comment]
@giuseppesorce If it's not related, you are doing something incorrectly. As sending either data or notification or both works for me (when using XMPP connection). Please follow the docs at: https://developers.google.com/cloud-messaging/

**Comment by pravat77** [comment]
Hi,

we are using Same property as GcmSender class. But at the time of OutputStream outputStream = conn.getOutputStream(); throwing an exception. COnnection Refused.

Thanks & regards,
Pravat Dash.

**Comment by joelSimpson** [comment]
Currently having the same issue.  When trying to submit a payload with the notification tag, I'm constantly receiving an InternalServerError.  I need this tag for iOS so that the device shows a banner notification when the app is in the background.

Is no one else seeing this behaviour?

**Comment by alibitek** [comment]
@pravat77 @joelSimpson That's normal behavior as documented in the [GCM Connection Server Reference](https://developers.google.com/cloud-messaging/server-ref) documentation.
- [Interpreting a downstream HTTP message response]() section
  `5xx    Errors in the 500-599 range (such as 500 or 503) indicate that there was an internal error in the GCM connection server while trying to process the request, or that the server is temporarily unavailable (for example, because of timeouts). Sender must retry later, honoring any Retry-After header included in the response. Application servers must implement exponential back-off. Troubleshoot
  `
- [Downstream message error response codes (HTTP and XMPP)](https://developers.google.com/cloud-messaging/server-ref#error-codes)
  `Timeout    5xx or 200 + error:Unavailable  SERVICE_UNAVAILABLE 
  The server couldn't process the request in time. Retry the same request, but you must:
  For HTTP: Honor the Retry-After header if it is included in the response from the GCM Connection Server.
  Implement exponential back-off in your retry mechanism. (e.g. if you waited one second before the first retry, wait at least two second before the next one, then 4 seconds and so on). If you're sending multiple messages, delay each one independently by an additional random amount to avoid issuing a new request for all messages at the same time.
  For CCS: The initial retry delay should be set to 1 second.
  Senders that cause problems risk being blacklisted.`

`Internal Server Error  500 or 200 + error:InternalServerError  INTERNAL_SERVER_ 
ERROR   The server encountered an error while trying to process the request. You could retry the same request following the requirements listed in "Timeout" (see row above). If the error persists, please report the problem in the android-gcm group.
`

You should implement a retry mechanism using an [exponential back-off strategy](https://en.wikipedia.org/wiki/Exponential_backoff) [HTTP, XMPP] and honor the Retry-After header [HTTP]

**Comment by mbernier85** [comment]
@mnemonicflow We are not yet to the point of server code, we are just trying to send notification with CURL, and it's not working.

It's been like this for days, even if we change the registration id of the device.

When we send a payload with just "data" and no "notification" it works.

**Comment by alibitek** [comment]
@mbernier85 Are you using an HTTP or XMPP connection?

BTW, if your app is in the published state (either: production, alpha, beta testing) you can have access to some GCM statistics, message status and diagnostics where you can troubleshoot messages sent through GCM. 
As per the following help guide you need to follow some steps to get access to such tools: https://support.google.com/googleplay/android-developer/answer/2663268

**Comment by mbernier85** [comment]
@mnemonicflow we've done this already, but the app is not in production yet for push, because we can't even send push in Dev and test properly ...

It's using HTTP with json

**Comment by mbernier85** [comment]
So, no one from Google read these issues ?

It's been broken for a week.

We redid a new project on the console, new keys, new registration Id.

The notification Key in payload doesn't work for iOS. It just returns InternalServerErrors.

**Comment by silvolu** [comment]
@mbernier85 we are aware of this issue and we are investigating the root causes. I'll update this thread as soon as we know more.
Apologies for the delay in replying; this issue tracker is meant for the sample code contained in the repo, and we monitor it on a best-effort basis.

**Comment by mbernier85** [comment]
@silvolu I even sent email on the GCM website from the Send Feedback link, no response.

Where am I suppose to contact support ?

**Comment by alibitek** [comment]
@mbernier85 https://groups.google.com/forum/#!forum/android-gcm

**Comment by StephenStrickland** [comment]
@silvolu any updates?

**Comment by silvolu** [comment]
We are trying to get better error reporting for this, but after some investigation, we think that the most likely causes are problems with the APNS certificate, which mostly should be one of:
1. using a revoked certificate
2. using a sandbox credential to connect to the production Apple server or vice versa

For 2., you need to set  `kGGLInstanceIDAPNSServerTypeSandboxOption` accordingly when calling `GGLInstanceID:tokenWithAuthorizedEntity`, as described in step 3 of the "Obtain a GCM Registration Token" section in the [iOS implementation guide](https://developers.google.com/cloud-messaging/ios/client#obtain_a_gcm_registration_token).

Could any of those 2 be your issue?

**Comment by StephenStrickland** [comment]
@silvolu at least for me we are not using a revoked certificate (I can use it to push manually through APNS) and we in production mode for all of our push notifications (but just to be sure I will have another pair of eyes recheck). If you need anything else, files, registration tokens, api keys, let me know.

**Comment by mbernier85** [comment]
@silvolu we took another look at our stuff, we are using the Sandbox certificate and Dev version of our app, and the certificates are all up to date and working.

Our next step is to test our cert with our own Push server

What I don't understand is, what changed on your side that made the push stop working, because it worked perfectly for a couple of days, and then stopped working.

I know you guys are working on better error handling.

We thought we could save time by using GCM for both iOS and Android, but right now we think we might have to develop both on our side.

**Comment by WilliamHua** [comment]
Any updates on this? Having the same issue. 

I am able to push successfully to my device with APNS. I configured the GCM HTTP Server correctly and all of a sudden it stopped working.

**Comment by pascualguerreroc** [comment]
@silvolu  I have the same problem, any help? this error only occurs when using the notification tag

**Comment by mostafaberg** [comment]
This still doesn't work btw, to reproduce simply use the example code, now the `GcmServerDemo` fails to send the message if it has a `notification` field in the call, it will say success though, but upon investigation and using the curl command, it responds with `InternalServerError`, after reading the proper response body in the `GcmServerDemo`, it also shows the same error message, so don't take it's word "success" on that ;), any tips or updates ?

**Comment by juliancesar** [comment]
Any updates on this? Having the same issue.

**Comment by ogeidix** [comment]
I believe different issues are being reported in this single thread.
@mostafaberg, @juliancesar if you are still experiencing issues, could you report them here:
https://support.google.com/code/contact/gcm_dev_support

Or, if your issue is with the code in this repo, please open a new bug.

Thanks, Diego.
